import type { OperatorApp } from "./desktop";

// Fallback-only catalog used when the Tauri allowlist cannot be queried. The
// Rust OPERATOR_APPS allowlist remains launch authority; keep ids in parity.
export const FALLBACK_OPERATOR_APPS: OperatorApp[] = [
  {
    id: "terminal",
    label: "Terminal",
    description: "Open a Foot terminal in the current FORGE operator session.",
    executable: "foot",
    category: "Workspace",
    iconName: "foot",
    iconPath: "/run/current-system/sw/share/icons/hicolor/48x48/apps/foot.png",
    desktopFile: "/run/current-system/sw/share/applications/foot.desktop",
    native: true,
  },
  {
    id: "files",
    label: "Files",
    description: "Open the PCManFM file manager in the current FORGE operator session.",
    executable: "pcmanfm",
    category: "Workspace",
    iconName: "system-file-manager",
    iconPath: null,
    desktopFile: "/run/current-system/sw/share/applications/pcmanfm.desktop",
    native: true,
  },
  {
    id: "editor",
    label: "Editor",
    description: "Open the native Mousepad text editor.",
    executable: "mousepad",
    category: "Workspace",
    iconName: "accessories-text-editor",
    iconPath: null,
    desktopFile: "/run/current-system/sw/share/applications/org.xfce.mousepad.desktop",
    native: true,
  },
  {
    id: "archive-manager",
    label: "Archive Manager",
    description: "Open Xarchiver for inspecting and unpacking local archives.",
    executable: "xarchiver",
    category: "Workspace",
    iconName: "package-x-generic",
    iconPath: null,
    desktopFile: "/run/current-system/sw/share/applications/xarchiver.desktop",
    native: true,
  },
  {
    id: "browser",
    label: "Browser",
    description: "Open Firefox for local docs, web consoles, and model tooling.",
    executable: "firefox",
    category: "Internet",
    iconName: "firefox",
    iconPath: "/run/current-system/sw/share/icons/hicolor/128x128/apps/firefox.png",
    desktopFile: "/run/current-system/sw/share/applications/firefox.desktop",
    native: true,
  },
  {
    id: "api-health",
    label: "API Health",
    description: "Run a fixed FORGE core health probe in a terminal.",
    executable: "foot",
    category: "Internet",
    iconName: "utilities-terminal",
    iconPath: null,
    desktopFile: null,
    native: false,
  },
  {
    id: "ollama-status",
    label: "Ollama Status",
    description: "Show local Ollama process and model status without loading or unloading models.",
    executable: "foot",
    category: "AI Runtime",
    iconName: "utilities-terminal",
    iconPath: null,
    desktopFile: null,
    native: false,
  },
  {
    id: "modelruntime-status",
    label: "Modelruntime Status",
    description: "Show governed FORGE modelruntime status through the local core API.",
    executable: "foot",
    category: "AI Runtime",
    iconName: "utilities-terminal",
    iconPath: null,
    desktopFile: null,
    native: false,
  },
  {
    id: "system-monitor",
    label: "System Monitor",
    description: "Open the fixed btop/htop process monitor wrapper.",
    executable: "foot",
    category: "System",
    iconName: "utilities-system-monitor",
    iconPath: null,
    desktopFile: null,
    native: false,
  },
  {
    id: "core-logs",
    label: "Core Logs",
    description: "Show recent forge-core journal logs through a fixed read-only wrapper.",
    executable: "foot",
    category: "System",
    iconName: "text-x-log",
    iconPath: null,
    desktopFile: null,
    native: false,
  },
  {
    id: "network-diagnostics",
    label: "Network Diagnostics",
    description: "Show fixed read-only address, route, socket, and DNS diagnostics.",
    executable: "foot",
    category: "System",
    iconName: "network-workgroup",
    iconPath: null,
    desktopFile: null,
    native: false,
  },
  {
    id: "hardware-diagnostics",
    label: "Hardware Diagnostics",
    description: "Show fixed read-only PCI, USB, and process file diagnostics.",
    executable: "foot",
    category: "System",
    iconName: "utilities-system-monitor",
    iconPath: null,
    desktopFile: null,
    native: false,
  },
  {
    id: "sqlite-browser",
    label: "SQLite Browser",
    description: "Open DB Browser for SQLite for local database inspection.",
    executable: "sqlitebrowser",
    category: "Developer",
    iconName: "sqlitebrowser",
    iconPath: null,
    desktopFile: "/run/current-system/sw/share/applications/sqlitebrowser.desktop",
    native: true,
  },
  {
    id: "lazygit",
    label: "Git UI",
    description: "Open lazygit in the FORGE workspace through a fixed terminal wrapper.",
    executable: "foot",
    category: "Developer",
    iconName: "git",
    iconPath: null,
    desktopFile: null,
    native: false,
  },
  {
    id: "forge-status",
    label: "FORGE Status",
    description: "Show local forge-core health through a fixed read-only wrapper.",
    executable: "foot",
    category: "FORGE",
    iconName: "utilities-terminal",
    iconPath: null,
    desktopFile: null,
    native: false,
  },
];
