package autonomy

import "forge/projectforge/services/core/internal/aios/domain"

func DefaultBudgets(scope domain.ForgeScope, now int64, createdBy string) []domain.FreedomBudget {
	if now <= 0 {
		now = domain.NowMillis()
	}
	cost := 250
	return []domain.FreedomBudget{
		{
			ID:                             "budget_memory_maintenance",
			Name:                           "Memory Maintenance Budget",
			Scope:                          scope,
			Status:                         domain.BudgetStatusActive,
			Period:                         domain.BudgetPeriodDaily,
			MaxSelfActionsPerRun:           20,
			MaxRunsPerPeriod:               6,
			MaxCommittedActionsPerPeriod:   80,
			MaxProposedActionsPerPeriod:    120,
			MaxInternalToolCalls:           20,
			MaxExternalCallsWithoutApprove: 0,
			MaxArchiveActions:              5,
			MaxContextPrecompilations:      4,
			MaxProjectionRebuilds:          2,
			MaxRuleAgentRuns:               8,
			MaxCostUnits:                   &cost,
			Usage:                          domain.FreedomBudgetUsage{},
			ResetsAt:                       now + int64(24*60*60*1000),
			CreatedAt:                      now,
			UpdatedAt:                      now,
			Metadata:                       map[string]any{"createdBy": createdBy},
		},
		{
			ID:                             "budget_context_prep",
			Name:                           "Context Preparation Budget",
			Scope:                          scope,
			Status:                         domain.BudgetStatusActive,
			Period:                         domain.BudgetPeriodDaily,
			MaxSelfActionsPerRun:           8,
			MaxRunsPerPeriod:               8,
			MaxCommittedActionsPerPeriod:   20,
			MaxProposedActionsPerPeriod:    40,
			MaxInternalToolCalls:           10,
			MaxExternalCallsWithoutApprove: 0,
			MaxArchiveActions:              0,
			MaxContextPrecompilations:      10,
			MaxProjectionRebuilds:          2,
			MaxRuleAgentRuns:               4,
			Usage:                          domain.FreedomBudgetUsage{},
			ResetsAt:                       now + int64(24*60*60*1000),
			CreatedAt:                      now,
			UpdatedAt:                      now,
			Metadata:                       map[string]any{"createdBy": createdBy},
		},
	}
}

func DefaultCharters(scope domain.ForgeScope, now int64, createdBy string) []domain.AutonomyCharter {
	if now <= 0 {
		now = domain.NowMillis()
	}
	return []domain.AutonomyCharter{
		{
			ID:             "charter_memory_maintenance",
			Name:           "MemoryMaintenanceCharter",
			Description:    "Allow safe internal memory hygiene and diagnostics.",
			Scope:          scope,
			Status:         domain.CharterActive,
			Purpose:        "Allow FORGE to keep memory clean and useful.",
			AllowedActions: []domain.SemanticActionType{domain.ActionCreateLink, domain.ActionCreateNote, domain.ActionRegisterContradict, domain.ActionCompileContext},
			DeniedActions:  []domain.SemanticActionType{"DELETE_ARTIFACT", "EXTERNAL_SEND", "CHANGE_PERMISSION", "DELETE_FILE"},
			ConditionalActions: []domain.ConditionRule{
				{
					Action:           domain.ActionArchiveNote,
					Conditions:       []string{"note.status == superseded", "age_days > 30", "no_active_state_depends_on_note"},
					MaxRisk:          domain.AutonomyRiskLow,
					RequiresEvidence: true,
				},
			},
			RequiresApprovalActions: []domain.SemanticActionType{domain.ActionMarkSuperseded, domain.ActionCloseLoop, domain.ActionUpdateState},
			AllowedSources:          []domain.IntentSource{domain.IntentSourceForge, domain.IntentSourceRuleAgent, domain.IntentSourceCell, domain.IntentSourceSystem, domain.IntentSourceTest},
			RiskLimits:              []domain.AutonomyRisk{domain.AutonomyRiskLow, domain.AutonomyRiskMedium},
			FreedomBudgetID:         "budget_memory_maintenance",
			EffectiveFrom:           now,
			CreatedBy:               createdBy,
			ApprovedBy:              createdBy,
			Provenance:              domain.Provenance{Actor: createdBy, ActorType: "system", Source: "autonomy.defaults"},
			CreatedAt:               now,
			UpdatedAt:               now,
			Metadata:                map[string]any{"default": true},
		},
		{
			ID:                      "charter_open_loop_review",
			Name:                    "OpenLoopReviewCharter",
			Description:             "Allow stale-loop review notes and diagnostics.",
			Scope:                   scope,
			Status:                  domain.CharterActive,
			Purpose:                 "Allow stale-loop detection and review notes.",
			AllowedActions:          []domain.SemanticActionType{domain.ActionCreateNote, domain.ActionUpdateState},
			DeniedActions:           []domain.SemanticActionType{"DELETE_ARTIFACT", "EXTERNAL_SEND", "CHANGE_PERMISSION", "DELETE_FILE"},
			RequiresApprovalActions: []domain.SemanticActionType{domain.ActionCloseLoop},
			AllowedSources:          []domain.IntentSource{domain.IntentSourceForge, domain.IntentSourceRuleAgent, domain.IntentSourceSystem, domain.IntentSourceTest},
			RiskLimits:              []domain.AutonomyRisk{domain.AutonomyRiskLow, domain.AutonomyRiskMedium},
			FreedomBudgetID:         "budget_memory_maintenance",
			EffectiveFrom:           now,
			CreatedBy:               createdBy,
			ApprovedBy:              createdBy,
			Provenance:              domain.Provenance{Actor: createdBy, ActorType: "system", Source: "autonomy.defaults"},
			CreatedAt:               now,
			UpdatedAt:               now,
			Metadata:                map[string]any{"default": true},
		},
		{
			ID:                      "charter_context_preparation",
			Name:                    "ContextPreparationCharter",
			Description:             "Allow FORGE to prepare internal context packets.",
			Scope:                   scope,
			Status:                  domain.CharterActive,
			Purpose:                 "Allow FORGE to prepare context packet preflight snapshots.",
			AllowedActions:          []domain.SemanticActionType{domain.ActionCompileContext, domain.ActionCreateNote},
			DeniedActions:           []domain.SemanticActionType{"EXTERNAL_SEND", "DELETE_ARTIFACT", "DELETE_FILE"},
			RequiresApprovalActions: []domain.SemanticActionType{"EXTERNAL_EXPORT"},
			AllowedSources:          []domain.IntentSource{domain.IntentSourceForge, domain.IntentSourceRuleAgent, domain.IntentSourceCell, domain.IntentSourceSystem, domain.IntentSourceTest},
			RiskLimits:              []domain.AutonomyRisk{domain.AutonomyRiskLow, domain.AutonomyRiskMedium},
			FreedomBudgetID:         "budget_context_prep",
			EffectiveFrom:           now,
			CreatedBy:               createdBy,
			ApprovedBy:              createdBy,
			Provenance:              domain.Provenance{Actor: createdBy, ActorType: "system", Source: "autonomy.defaults"},
			CreatedAt:               now,
			UpdatedAt:               now,
			Metadata:                map[string]any{"default": true},
		},
		{
			ID:                      "charter_projection_repair",
			Name:                    "ProjectionRepairCharter",
			Description:             "Allow dry-run projection repair diagnostics.",
			Scope:                   scope,
			Status:                  domain.CharterActive,
			Purpose:                 "Allow projection rebuild dry-runs and deterministic repair diagnostics.",
			AllowedActions:          []domain.SemanticActionType{domain.ActionCreateNote, domain.ActionCreateLink, domain.ActionCompileContext},
			DeniedActions:           []domain.SemanticActionType{"DELETE_ARTIFACT", "DELETE_FILE", "EXTERNAL_SEND"},
			RequiresApprovalActions: []domain.SemanticActionType{domain.ActionUpdateState, domain.ActionArchiveNote, domain.ActionMarkSuperseded},
			AllowedSources:          []domain.IntentSource{domain.IntentSourceForge, domain.IntentSourceRuleAgent, domain.IntentSourceSystem, domain.IntentSourceTest},
			RiskLimits:              []domain.AutonomyRisk{domain.AutonomyRiskLow},
			FreedomBudgetID:         "budget_memory_maintenance",
			EffectiveFrom:           now,
			CreatedBy:               createdBy,
			ApprovedBy:              createdBy,
			Provenance:              domain.Provenance{Actor: createdBy, ActorType: "system", Source: "autonomy.defaults"},
			CreatedAt:               now,
			UpdatedAt:               now,
			Metadata:                map[string]any{"default": true},
		},
	}
}
